name: Update Strava Data

on:
  workflow_dispatch:       # manuell starten
  schedule:
    - cron: "0 5 * * *"    # täglich 05:00 UTC

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch Strava activities
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: node scripts/fetch_strava.js

      - name: Commit & push data file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/strava.json
          git commit -m "chore: update Strava data" || echo "No changes to commit"
          git push
